version: "3.9"

services:
  backend:
    build: .
    container_name: ai-detector-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./react-app
    container_name: ai-detector-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
